In [159]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/medical_insurance_with_claim_date_v2.csv')
df

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
0,CLM1000,PAT5100,POL9291,HSP57,NaN,97.0,F,john@,98765 43210,Mumbai,...,96.0,Cahs,Failed,57.0,5,Poor,Alex,Active,No,2024-01-16
1,CLM1001,PAT7122,POL1727,HSP106,Priya,35.0,F,NaN,NaN,NaN,...,21.0,Online,Failed,81.0,3,Average,NaN,Inactive,No,2024-02-14
2,CLM1002,PAT7837,POL4305,HSP25,Amit,53.0,Male,amit@yahoo.com,NaN,Mumbai,...,90.0,Card,Paid,62.0,3,Good,Tom,Inactive,NaN,2024-04-17
3,CLM1003,PAT2862,POL1759,HSP498,NaN,33.0,Mle,john@,NaN,NaN,...,59.0,Cahs,NaN,23.0,1,Average,NaN,Inactive,Yes,2024-11-07
4,CLM1004,PAT980,POL7294,HSP348,Ravi,-3.0,Female,amit@yahoo.com,98765 43210,NaN,...,91.0,Card,Failed,13.0,0,Poor,NaN,Active,Yes,2024-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21
9996,CLM10996,PAT2175,POL5818,HSP191,Amit,17.0,Female,john@,12345,Mumbai,...,NaN,Online,Failed,-2.0,4,NaN,NaN,Closed,Yes,2024-07-17
9997,CLM10997,PAT2292,POL3010,HSP18,Mary,125.0,Female,NaN,NaN,Mumbai,...,27.0,Cash,Pending,85.0,1,Good,Alex,Inactive,No,2025-08-25
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13
9999,CLM10999,PAT479,POL5399,HSP203,Mary,58.0,Female,mary@gmail.com,9876543210,Chennai,...,58.0,Cash,Failed,NaN,4,Average,NaN,Closed,No,2026-03-02

All column names

In [160]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date'],
      dtype='object')

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Claim_ID                    10000 non-null  object
 1   Patient_ID                  10000 non-null  object
 2   Policy_ID                   10000 non-null  object
 3   Hospital_ID                 10000 non-null  object
 4   Name                        8571 non-null   object
 5   Age                         9500 non-null   float64
 6   Gender                      10000 non-null  object
 7   Email                       7980 non-null   object
 8   Phone                       7510 non-null   object
 9   Address                     8324 non-null   object
 10  City                        8301 non-null   object
 11  Country                     8043 non-null   object
 12  Diagnosis                   8371 non-null   object
 13  Disease_Category            7568 non-null   object
 14  Doctor_Name                 7987 non-null   object
 15  Treatment_Start_Date        10000 non-null  object
 16  Treatment_End_Date          10000 non-null  object
 17  Hospital_Name               7942 non-null   object
 18  Insurance_Type              7487 non-null   object
 19  Claim_Amount                9500 non-null   float64
 20  Approved_Amount             9500 non-null   float64
 21  Claim_Status                10000 non-null  object
 22  Policy_Start_Date           10000 non-null  object
 23  Policy_End_Date             10000 non-null  object
 24  Deductible_Amount           9500 non-null   float64
 25  CoPay_Percentage            9500 non-null   float64
 26  Payment_Mode                8004 non-null   object
 27  Payment_Status              7575 non-null   object
 28  Reimbursement_Days          9500 non-null   float64
 29  Patient_Satisfaction_Score  10000 non-null  int64
 30  Feedback                    7463 non-null   object
 31  Agent_Name                  7962 non-null   object
 32  Account_Status              10000 non-null  object
 33  Followup_Required           6634 non-null   object
 34  Claim_Date                  10000 non-null  object
dtypes: float64(6), int64(1), object(28)
memory usage: 2.7+ MB

In [162]:
df.shape

(10000, 35)

Identify Duplicate Rows

In [163]:
df.duplicated().sum()

np.int64(0)

Remove Duplicate Rows

In [164]:
df.drop_duplicates()

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
0,CLM1000,PAT5100,POL9291,HSP57,NaN,97.0,F,john@,98765 43210,Mumbai,...,96.0,Cahs,Failed,57.0,5,Poor,Alex,Active,No,2024-01-16
1,CLM1001,PAT7122,POL1727,HSP106,Priya,35.0,F,NaN,NaN,NaN,...,21.0,Online,Failed,81.0,3,Average,NaN,Inactive,No,2024-02-14
2,CLM1002,PAT7837,POL4305,HSP25,Amit,53.0,Male,amit@yahoo.com,NaN,Mumbai,...,90.0,Card,Paid,62.0,3,Good,Tom,Inactive,NaN,2024-04-17
3,CLM1003,PAT2862,POL1759,HSP498,NaN,33.0,Mle,john@,NaN,NaN,...,59.0,Cahs,NaN,23.0,1,Average,NaN,Inactive,Yes,2024-11-07
4,CLM1004,PAT980,POL7294,HSP348,Ravi,-3.0,Female,amit@yahoo.com,98765 43210,NaN,...,91.0,Card,Failed,13.0,0,Poor,NaN,Active,Yes,2024-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21
9996,CLM10996,PAT2175,POL5818,HSP191,Amit,17.0,Female,john@,12345,Mumbai,...,NaN,Online,Failed,-2.0,4,NaN,NaN,Closed,Yes,2024-07-17
9997,CLM10997,PAT2292,POL3010,HSP18,Mary,125.0,Female,NaN,NaN,Mumbai,...,27.0,Cash,Pending,85.0,1,Good,Alex,Inactive,No,2025-08-25
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13
9999,CLM10999,PAT479,POL5399,HSP203,Mary,58.0,Female,mary@gmail.com,9876543210,Chennai,...,58.0,Cash,Failed,NaN,4,Average,NaN,Closed,No,2026-03-02

Remove Duplicate Claim_ID

In [165]:
df.drop_duplicates(subset="Claim_ID")

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
0,CLM1000,PAT5100,POL9291,HSP57,NaN,97.0,F,john@,98765 43210,Mumbai,...,96.0,Cahs,Failed,57.0,5,Poor,Alex,Active,No,2024-01-16
1,CLM1001,PAT7122,POL1727,HSP106,Priya,35.0,F,NaN,NaN,NaN,...,21.0,Online,Failed,81.0,3,Average,NaN,Inactive,No,2024-02-14
2,CLM1002,PAT7837,POL4305,HSP25,Amit,53.0,Male,amit@yahoo.com,NaN,Mumbai,...,90.0,Card,Paid,62.0,3,Good,Tom,Inactive,NaN,2024-04-17
3,CLM1003,PAT2862,POL1759,HSP498,NaN,33.0,Mle,john@,NaN,NaN,...,59.0,Cahs,NaN,23.0,1,Average,NaN,Inactive,Yes,2024-11-07
4,CLM1004,PAT980,POL7294,HSP348,Ravi,-3.0,Female,amit@yahoo.com,98765 43210,NaN,...,91.0,Card,Failed,13.0,0,Poor,NaN,Active,Yes,2024-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21
9996,CLM10996,PAT2175,POL5818,HSP191,Amit,17.0,Female,john@,12345,Mumbai,...,NaN,Online,Failed,-2.0,4,NaN,NaN,Closed,Yes,2024-07-17
9997,CLM10997,PAT2292,POL3010,HSP18,Mary,125.0,Female,NaN,NaN,Mumbai,...,27.0,Cash,Pending,85.0,1,Good,Alex,Inactive,No,2025-08-25
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13
9999,CLM10999,PAT479,POL5399,HSP203,Mary,58.0,Female,mary@gmail.com,9876543210,Chennai,...,58.0,Cash,Failed,NaN,4,Average,NaN,Closed,No,2026-03-02

Remove Duplicate Patient_ID

In [166]:
df.drop_duplicates(subset="Patient_ID")

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
0,CLM1000,PAT5100,POL9291,HSP57,NaN,97.0,F,john@,98765 43210,Mumbai,...,96.0,Cahs,Failed,57.0,5,Poor,Alex,Active,No,2024-01-16
1,CLM1001,PAT7122,POL1727,HSP106,Priya,35.0,F,NaN,NaN,NaN,...,21.0,Online,Failed,81.0,3,Average,NaN,Inactive,No,2024-02-14
2,CLM1002,PAT7837,POL4305,HSP25,Amit,53.0,Male,amit@yahoo.com,NaN,Mumbai,...,90.0,Card,Paid,62.0,3,Good,Tom,Inactive,NaN,2024-04-17
3,CLM1003,PAT2862,POL1759,HSP498,NaN,33.0,Mle,john@,NaN,NaN,...,59.0,Cahs,NaN,23.0,1,Average,NaN,Inactive,Yes,2024-11-07
4,CLM1004,PAT980,POL7294,HSP348,Ravi,-3.0,Female,amit@yahoo.com,98765 43210,NaN,...,91.0,Card,Failed,13.0,0,Poor,NaN,Active,Yes,2024-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,15.0,Card,NaN,1.0,4,Average,NaN,Active,NaN,2024-10-23
9989,CLM10989,PAT2870,POL8054,HSP479,NaN,26.0,Mle,amit@yahoo.com,12345,NaN,...,41.0,NaN,Pending,19.0,3,NaN,Sita,Inactive,Yes,2025-05-03
9992,CLM10992,PAT5061,POL2958,HSP333,Priya,80.0,F,ravi,NaN,Delhi,...,51.0,NaN,Failed,33.0,3,Good,Rahul,Inactive,No,2025-04-08
9993,CLM10993,PAT2884,POL1742,HSP275,Ravi,39.0,Mle,mary@gmail.com,98765 43210,New York,...,98.0,Cash,Failed,39.0,3,Poor,Sita,Active,No,2024-09-16
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21

Remove Duplicate Email

In [167]:
df.drop_duplicates(subset="Email")

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
0,CLM1000,PAT5100,POL9291,HSP57,NaN,97.0,F,john@,98765 43210,Mumbai,...,96.0,Cahs,Failed,57.0,5,Poor,Alex,Active,No,2024-01-16
1,CLM1001,PAT7122,POL1727,HSP106,Priya,35.0,F,NaN,NaN,NaN,...,21.0,Online,Failed,81.0,3,Average,NaN,Inactive,No,2024-02-14
2,CLM1002,PAT7837,POL4305,HSP25,Amit,53.0,Male,amit@yahoo.com,NaN,Mumbai,...,90.0,Card,Paid,62.0,3,Good,Tom,Inactive,NaN,2024-04-17
7,CLM1007,PAT2735,POL5797,HSP10,NaN,20.0,F,ravi,98765 43210,New York,...,NaN,Card,Failed,NaN,2,Poor,Sita,Inactive,NaN,2024-03-03
9,CLM1009,PAT1173,POL4586,HSP284,Ravi,73.0,Other,mary@gmail.com,NaN,NaN,...,47.0,Online,Pending,92.0,3,Good,Rahul,Active,No,2026-03-04

Check Missing Values

In [168]:
df.isnull().sum()

Claim_ID                         0
Patient_ID                       0
Policy_ID                        0
Hospital_ID                      0
Name                          1429
Age                            500
Gender                           0
Email                         2020
Phone                         2490
Address                       1676
City                          1699
Country                       1957
Diagnosis                     1629
Disease_Category              2432
Doctor_Name                   2013
Treatment_Start_Date             0
Treatment_End_Date               0
Hospital_Name                 2058
Insurance_Type                2513
Claim_Amount                   500
Approved_Amount                500
Claim_Status                     0
Policy_Start_Date                0
Policy_End_Date                  0
Deductible_Amount              500
CoPay_Percentage               500
Payment_Mode                  1996
Payment_Status                2425
Reimbursement_Days             500
Patient_Satisfaction_Score       0
Feedback                      2537
Agent_Name                    2038
Account_Status                   0
Followup_Required             3366
Claim_Date                       0
dtype: int64

Fill Missing Name

In [169]:
df["Name"].fillna("Unknown")

0       Unknown
1         Priya
2          Amit
3       Unknown
4          Ravi
         ...
9995       Ravi
9996       Amit
9997       Mary
9998       Ravi
9999       Mary
Name: Name, Length: 10000, dtype: object

Fill Missing Email

In [170]:
df["Email"] = df["Email"].fillna("noemail@example.com")
df["Email"]

0                     john@
1       noemail@example.com
2            amit@yahoo.com
3                     john@
4            amit@yahoo.com
               ...
9995                   ravi
9996                  john@
9997    noemail@example.com
9998                  john@
9999         mary@gmail.com
Name: Email, Length: 10000, dtype: object

Fill Missing Hospital Name

In [171]:
df["Hospital_Name"] = df["Hospital_Name"].fillna("Not Available")
df["Hospital_Name"]

0        AIIMS
1        AIIMS
2       Global
3       Apollo
4        AIIMS
         ...
9995    Apollo
9996    Fortis
9997    Fortis
9998     AIIMS
9999    Apollo
Name: Hospital_Name, Length: 10000, dtype: object

Fill Missing Insurance Type

In [172]:
df["Insurance_Type"] = df["Insurance_Type"].fillna("General")
df["Insurance_Type"]

0       General
1         Basic
2       Premium
3       General
4       General
         ...
9995    General
9996    General
9997    General
9998    Premium
9999    General
Name: Insurance_Type, Length: 10000, dtype: object

Fill Missing Claim Amount (Mean by Disease Category)

In [173]:
df["Claim_Amount"] = df["Claim_Amount"].fillna(
    df.groupby("Disease_Category")["Claim_Amount"].transform("mean"))
df["Claim_Amount"]

0         7992.000000
1       120873.000000
2        94817.855893
3        80931.000000
4       145638.000000
            ...
9995     90069.000000
9996     19586.000000
9997     59538.000000
9998    159645.000000
9999    178966.000000
Name: Claim_Amount, Length: 10000, dtype: float64

Fill Missing Approved Amount (Median by Insurance Type)

In [174]:
df["Approved_Amount"] = df["Approved_Amount"].fillna(
    df.groupby("Insurance_Type")["Approved_Amount"].transform("median"))
df["Approved_Amount"]

0       141736.0
1       132462.0
2       131928.0
3       128273.0
4        75962.0
          ...
9995     70736.0
9996    110996.0
9997     78550.0
9998    135339.0
9999    156195.0
Name: Approved_Amount, Length: 10000, dtype: float64

In [175]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date'],
      dtype='object')

# **Section B — Invalid / Outlier Values**

Remove Claim_Amount < 0

In [176]:
df = df[df["Claim_Amount"] >= 0]
df

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
0,CLM1000,PAT5100,POL9291,HSP57,NaN,97.0,F,john@,98765 43210,Mumbai,...,96.0,Cahs,Failed,57.0,5,Poor,Alex,Active,No,2024-01-16
1,CLM1001,PAT7122,POL1727,HSP106,Priya,35.0,F,noemail@example.com,NaN,NaN,...,21.0,Online,Failed,81.0,3,Average,NaN,Inactive,No,2024-02-14
2,CLM1002,PAT7837,POL4305,HSP25,Amit,53.0,Male,amit@yahoo.com,NaN,Mumbai,...,90.0,Card,Paid,62.0,3,Good,Tom,Inactive,NaN,2024-04-17
3,CLM1003,PAT2862,POL1759,HSP498,NaN,33.0,Mle,john@,NaN,NaN,...,59.0,Cahs,NaN,23.0,1,Average,NaN,Inactive,Yes,2024-11-07
4,CLM1004,PAT980,POL7294,HSP348,Ravi,-3.0,Female,amit@yahoo.com,98765 43210,NaN,...,91.0,Card,Failed,13.0,0,Poor,NaN,Active,Yes,2024-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21
9996,CLM10996,PAT2175,POL5818,HSP191,Amit,17.0,Female,john@,12345,Mumbai,...,NaN,Online,Failed,-2.0,4,NaN,NaN,Closed,Yes,2024-07-17
9997,CLM10997,PAT2292,POL3010,HSP18,Mary,125.0,Female,noemail@example.com,NaN,Mumbai,...,27.0,Cash,Pending,85.0,1,Good,Alex,Inactive,No,2025-08-25
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13
9999,CLM10999,PAT479,POL5399,HSP203,Mary,58.0,Female,mary@gmail.com,9876543210,Chennai,...,58.0,Cash,Failed,NaN,4,Average,NaN,Closed,No,2026-03-02

Remove Approved_Amount > Claim_Amount

In [177]:
df = df[df["Approved_Amount"] <= df["Claim_Amount"]]
df

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
4,CLM1004,PAT980,POL7294,HSP348,Ravi,-3.0,Female,amit@yahoo.com,98765 43210,NaN,...,91.0,Card,Failed,13.0,0,Poor,NaN,Active,Yes,2024-10-31
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
8,CLM1008,PAT2400,POL8572,HSP424,Mary,95.0,Female,noemail@example.com,NaN,New York,...,71.0,NaN,NaN,78.0,3,Good,Tom,Inactive,NaN,2025-10-23
10,CLM1010,PAT7309,POL7420,HSP204,NaN,-4.0,F,ravi,9876543210,New York,...,-7.0,Cahs,Paid,25.0,4,Good,Sita,Actve,Yes,2025-11-18
11,CLM1011,PAT9976,POL7227,HSP462,Ravi,121.0,Other,noemail@example.com,98765 43210,New York,...,89.0,NaN,NaN,71.0,1,Poor,Rahul,Inactive,NaN,2024-11-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CLM10989,PAT2870,POL8054,HSP479,NaN,26.0,Mle,amit@yahoo.com,12345,NaN,...,41.0,NaN,Pending,19.0,3,NaN,Sita,Inactive,Yes,2025-05-03
9993,CLM10993,PAT2884,POL1742,HSP275,Ravi,39.0,Mle,mary@gmail.com,98765 43210,New York,...,98.0,Cash,Failed,39.0,3,Poor,Sita,Active,No,2024-09-16
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13
9999,CLM10999,PAT479,POL5399,HSP203,Mary,58.0,Female,mary@gmail.com,9876543210,Chennai,...,58.0,Cash,Failed,NaN,4,Average,NaN,Closed,No,2026-03-02

Remove Invalid Age

In [178]:
df = df[(df["Age"] >= 0) & (df["Age"] <= 120)]
df

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
8,CLM1008,PAT2400,POL8572,HSP424,Mary,95.0,Female,noemail@example.com,NaN,New York,...,71.0,NaN,NaN,78.0,3,Good,Tom,Inactive,NaN,2025-10-23
14,CLM1014,PAT1892,POL6600,HSP21,Priya,111.0,Female,ravi,12345,Mumbai,...,76.0,Online,NaN,7.0,0,Poor,Alex,Actve,Yes,2025-01-20
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CLM10989,PAT2870,POL8054,HSP479,NaN,26.0,Mle,amit@yahoo.com,12345,NaN,...,41.0,NaN,Pending,19.0,3,NaN,Sita,Inactive,Yes,2025-05-03
9993,CLM10993,PAT2884,POL1742,HSP275,Ravi,39.0,Mle,mary@gmail.com,98765 43210,New York,...,98.0,Cash,Failed,39.0,3,Poor,Sita,Active,No,2024-09-16
9995,CLM10995,PAT5719,POL6054,HSP97,Ravi,20.0,Female,ravi,9876543210,New York,...,95.0,Cash,Failed,19.0,1,Poor,Rahul,Active,No,2024-02-21
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13
9999,CLM10999,PAT479,POL5399,HSP203,Mary,58.0,Female,mary@gmail.com,9876543210,Chennai,...,58.0,Cash,Failed,NaN,4,Average,NaN,Closed,No,2026-03-02

Convert Date Columns

In [179]:
df["Treatment_Start_Date"] = pd.to_datetime(df["Treatment_Start_Date"])
df["Treatment_End_Date"] = pd.to_datetime(df["Treatment_End_Date"])

df["Policy_Start_Date"] = pd.to_datetime(df["Policy_Start_Date"])
df["Policy_End_Date"] = pd.to_datetime(df["Policy_End_Date"])

df['Treatment_Start_Date']
df['Treatment_End_Date']
df['Policy_Start_Date']
df['Policy_End_Date']

/tmp/ipykernel_14451/3573397270.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Treatment_Start_Date"] = pd.to_datetime(df["Treatment_Start_Date"])
/tmp/ipykernel_14451/3573397270.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Treatment_End_Date"] = pd.to_datetime(df["Treatment_End_Date"])
/tmp/ipykernel_14451/3573397270.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Policy_Start_Date"] = pd.to_datetime(df["Policy_Start_Date"])
/tmp/ipykernel_14451/3573397270.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Policy_End_Date"] = pd.to_datetime(df["Policy_End_Date"])

5      2023-04-01
8      2020-01-28
14     2017-07-04
15     2024-02-10
16     2021-11-30
          ...
9989   2017-02-05
9993   2019-03-05
9995   2022-02-16
9998   2019-10-24
9999   2018-03-28
Name: Policy_End_Date, Length: 3983, dtype: datetime64[ns]

Remove Invalid Treatment Dates

In [180]:
df = df[df["Treatment_End_Date"] >= df["Treatment_Start_Date"]]
df

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,108.0,NaN,Pending,48.0,0,Good,Rahul,Actve,No,2026-02-14
40,CLM1040,PAT2211,POL1455,HSP4,Fatima,16.0,Other,john@,9876543210,London,...,-1.0,Cash,Failed,93.0,2,NaN,NaN,Active,Yes,2026-03-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,7.0,Online,Paid,22.0,3,Average,Sita,Closed,Yes,2025-07-19
9977,CLM10977,PAT7236,POL6010,HSP443,Priya,61.0,Mle,ravi,12345,London,...,71.0,Online,Failed,-3.0,1,Good,NaN,Closed,NaN,2025-10-27
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,15.0,Card,NaN,1.0,4,Average,NaN,Active,NaN,2024-10-23
9989,CLM10989,PAT2870,POL8054,HSP479,NaN,26.0,Mle,amit@yahoo.com,12345,NaN,...,41.0,NaN,Pending,19.0,3,NaN,Sita,Inactive,Yes,2025-05-03
9998,CLM10998,PAT5085,POL4118,HSP169,Ravi,23.0,F,john@,98765 43210,Chennai,...,7.0,Cash,Paid,NaN,5,NaN,Rahul,Closed,No,2025-11-13

Remove Invalid Policy Dates

In [181]:
df = df[df["Policy_End_Date"] >= df["Policy_Start_Date"]]
df

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,108.0,NaN,Pending,48.0,0,Good,Rahul,Actve,No,2026-02-14
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,-6.0,Cahs,Pending,2.0,3,Average,Rahul,Closed,Yes,2024-08-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,27.0,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,69.0,Cash,NaN,6.0,0,Poor,NaN,Closed,No,2025-05-19
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,7.0,Online,Paid,22.0,3,Average,Sita,Closed,Yes,2025-07-19
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,15.0,Card,NaN,1.0,4,Average,NaN,Active,NaN,2024-10-23

Fix Gender Typos

In [182]:
df["Gender"].replace({"Mle": "Male","F": "Female"})

5         Male
15       Other
16        Male
17       Other
42        Male
         ...
9959      Male
9962    Female
9965      Male
9967      Male
9984     Other
Name: Gender, Length: 1057, dtype: object

Fix Payment Mode Typos

In [183]:
df["Payment_Mode"].replace({"Cahs": "Cash"})

5         Cash
15        Card
16        Card
17         NaN
42        Cash
         ...
9959      Card
9962    Online
9965      Cash
9967    Online
9984      Card
Name: Payment_Mode, Length: 1057, dtype: object

Standardize Account Status

In [184]:
df["Account_Status"].str.capitalize()

5       Inactive
15         Actve
16         Actve
17         Actve
42        Closed
          ...
9959      Closed
9962       Actve
9965      Closed
9967      Closed
9984      Active
Name: Account_Status, Length: 1057, dtype: object

Remove Invalid Emails

In [185]:
df[df["Email"].str.contains("@", na=False)]
df[df["Email"].str.contains(".", na=False)]

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,108.0,NaN,Pending,48.0,0,Good,Rahul,Actve,No,2026-02-14
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,-6.0,Cahs,Pending,2.0,3,Average,Rahul,Closed,Yes,2024-08-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,27.0,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,69.0,Cash,NaN,6.0,0,Poor,NaN,Closed,No,2025-05-19
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,7.0,Online,Paid,22.0,3,Average,Sita,Closed,Yes,2025-07-19
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,15.0,Card,NaN,1.0,4,Average,NaN,Active,NaN,2024-10-23

In [186]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date'],
      dtype='object')

#**Section C — Conditional Filtering**

Claims > 100000

In [187]:
High_Amount = df[df["Claim_Amount"] > 100000]
High_Amount

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,108.0,NaN,Pending,48.0,0,Good,Rahul,Actve,No,2026-02-14
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,-6.0,Cahs,Pending,2.0,3,Average,Rahul,Closed,Yes,2024-08-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9958,CLM10958,PAT9586,POL8144,HSP394,Amit,22.0,Female,ravi,9876543210,Delhi,...,60.0,Online,Failed,72.0,3,Poor,Rahul,Active,NaN,2024-07-17
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,27.0,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,69.0,Cash,NaN,6.0,0,Poor,NaN,Closed,No,2025-05-19
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,15.0,Card,NaN,1.0,4,Average,NaN,Active,NaN,2024-10-23

Rejected Claims

In [188]:
rejected = df[df["Claim_Status"] == "Rejected"]
rejected

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
47,CLM1047,PAT8689,POL5800,HSP175,Priya,41.0,F,amit@yahoo.com,12345,Chennai,...,22.0,NaN,Failed,62.0,3,Average,Rahul,Closed,No,2024-02-14
62,CLM1062,PAT895,POL6125,HSP157,Mary,97.0,Other,ravi,98765 43210,NaN,...,36.0,Cash,Paid,15.0,5,NaN,NaN,Actve,No,2024-02-06
136,CLM1136,PAT989,POL1039,HSP36,NaN,35.0,F,mary@gmail.com,NaN,Delhi,...,104.0,Cahs,Pending,59.0,4,NaN,Rahul,Active,Yes,2025-06-27
145,CLM1145,PAT4573,POL5607,HSP274,NaN,52.0,Other,john@,12345,Chennai,...,70.0,Cahs,Failed,77.0,2,Poor,Sita,Actve,No,2025-07-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9909,CLM10909,PAT8990,POL4066,HSP484,Priya,0.0,Mle,john@,NaN,NaN,...,51.0,Card,NaN,NaN,2,Average,Rahul,Closed,Yes,2025-07-21
9920,CLM10920,PAT2774,POL3519,HSP156,Mary,117.0,F,mary@gmail.com,NaN,NaN,...,31.0,Online,Pending,75.0,0,Good,Tom,Closed,Yes,2025-03-19
9942,CLM10942,PAT4090,POL6760,HSP81,Mary,2.0,Mle,john@,NaN,NaN,...,2.0,NaN,Pending,22.0,3,Average,Alex,Active,No,2025-03-13
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,15.0,Card,NaN,1.0,4,Average,NaN,Active,NaN,2024-10-23

Premium Insurance

In [189]:
premium = df[df["Insurance_Type"] == "Premium"]
premium

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,0.0,Cahs,Paid,37.0,0,Average,NaN,Inactive,Yes,2025-08-08
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
47,CLM1047,PAT8689,POL5800,HSP175,Priya,41.0,F,amit@yahoo.com,12345,Chennai,...,22.0,NaN,Failed,62.0,3,Average,Rahul,Closed,No,2024-02-14
100,CLM1100,PAT8912,POL5225,HSP118,Fatima,58.0,Other,ravi,9876543210,NaN,...,100.0,Card,Failed,61.0,4,Poor,NaN,Active,Yes,2025-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9769,CLM10769,PAT7942,POL4538,HSP494,NaN,114.0,Female,john@,12345,Delhi,...,118.0,Cahs,Pending,95.0,5,NaN,NaN,Inactive,Yes,2026-02-13
9781,CLM10781,PAT9452,POL5323,HSP165,NaN,3.0,F,mary@gmail.com,12345,Mumbai,...,90.0,NaN,Failed,67.0,2,Average,Tom,Active,Yes,2024-08-30
9916,CLM10916,PAT3040,POL2556,HSP489,Mary,63.0,Mle,noemail@example.com,9876543210,NaN,...,37.0,NaN,Paid,-8.0,0,Average,Sita,Closed,NaN,2026-02-05
9958,CLM10958,PAT9586,POL8144,HSP394,Amit,22.0,Female,ravi,9876543210,Delhi,...,60.0,Online,Failed,72.0,3,Poor,Rahul,Active,NaN,2024-07-17
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21

Patients Age > 60

In [190]:
senior_patients = df[df["Age"] > 60]
senior_patients

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,108.0,NaN,Pending,48.0,0,Good,Rahul,Actve,No,2026-02-14
51,CLM1051,PAT5571,POL2615,HSP92,Ravi,84.0,Male,noemail@example.com,12345,Chennai,...,83.0,Card,Paid,48.0,0,Average,Tom,Inactive,Yes,2025-01-26
62,CLM1062,PAT895,POL6125,HSP157,Mary,97.0,Other,ravi,98765 43210,NaN,...,36.0,Cash,Paid,15.0,5,NaN,NaN,Actve,No,2024-02-06
90,CLM1090,PAT1232,POL2990,HSP216,Mary,73.0,Mle,john@,98765 43210,Chennai,...,15.0,Card,Pending,25.0,4,Good,NaN,Inactive,NaN,2025-05-01
108,CLM1108,PAT6171,POL7273,HSP213,NaN,91.0,F,noemail@example.com,12345,NaN,...,NaN,Online,NaN,-6.0,4,Poor,Alex,Closed,No,2024-09-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9955,CLM10955,PAT703,POL3139,HSP161,John,82.0,Male,mary@gmail.com,12345,London,...,28.0,NaN,Paid,50.0,5,Good,Sita,Actve,No,2024-08-13
9957,CLM10957,PAT9088,POL5705,HSP232,John,67.0,Female,amit@yahoo.com,NaN,NaN,...,28.0,Online,Pending,80.0,1,Average,Tom,Active,NaN,2024-06-15
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,27.0,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,7.0,Online,Paid,22.0,3,Average,Sita,Closed,Yes,2025-07-19

Claims from India

In [191]:
india_claims = df[df["Country"] == "India"]
india_claims

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
90,CLM1090,PAT1232,POL2990,HSP216,Mary,73.0,Mle,john@,98765 43210,Chennai,...,15.0,Card,Pending,25.0,4,Good,NaN,Inactive,NaN,2025-05-01
208,CLM1208,PAT1619,POL2872,HSP290,Priya,20.0,Male,john@,98765 43210,London,...,66.0,NaN,Paid,91.0,3,Average,Sita,Active,Yes,2024-01-25
210,CLM1210,PAT9404,POL8588,HSP230,Fatima,16.0,Other,amit@yahoo.com,12345,Mumbai,...,38.0,Cahs,NaN,35.0,2,Good,Sita,Closed,Yes,2024-08-01
228,CLM1228,PAT7873,POL6489,HSP22,NaN,11.0,Mle,noemail@example.com,9876543210,Delhi,...,44.0,NaN,Pending,97.0,0,Poor,NaN,Closed,NaN,2025-08-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9645,CLM10645,PAT5572,POL4354,HSP240,Mary,97.0,Other,noemail@example.com,NaN,London,...,4.0,Cahs,Paid,55.0,0,Average,Tom,Actve,No,2025-07-04
9689,CLM10689,PAT2606,POL7377,HSP177,Fatima,53.0,Mle,mary@gmail.com,NaN,London,...,NaN,Cash,Paid,62.0,0,Average,NaN,Inactive,NaN,2025-11-13
9703,CLM10703,PAT2428,POL2126,HSP56,NaN,44.0,Mle,mary@gmail.com,9876543210,NaN,...,20.0,Card,Paid,47.0,4,Average,Alex,Actve,Yes,2024-10-13
9757,CLM10757,PAT6484,POL4610,HSP384,Fatima,13.0,Male,amit@yahoo.com,12345,Delhi,...,38.0,NaN,Failed,73.0,0,Poor,Tom,Active,No,2024-05-13
9787,CLM10787,PAT1227,POL6275,HSP94,John,12.0,F,amit@yahoo.com,NaN,Mumbai,...,101.0,Online,Pending,-4.0,5,Good,Tom,Actve,No,2026-02-16

Copay > 20%

In [192]:
high_copay = df[df["CoPay_Percentage"] > 20]
high_copay

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,91.0,Card,Failed,14.0,0,Average,NaN,Actve,Yes,2024-12-15
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,108.0,NaN,Pending,48.0,0,Good,Rahul,Actve,No,2026-02-14
47,CLM1047,PAT8689,POL5800,HSP175,Priya,41.0,F,amit@yahoo.com,12345,Chennai,...,22.0,NaN,Failed,62.0,3,Average,Rahul,Closed,No,2024-02-14
51,CLM1051,PAT5571,POL2615,HSP92,Ravi,84.0,Male,noemail@example.com,12345,Chennai,...,83.0,Card,Paid,48.0,0,Average,Tom,Inactive,Yes,2025-01-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9957,CLM10957,PAT9088,POL5705,HSP232,John,67.0,Female,amit@yahoo.com,NaN,NaN,...,28.0,Online,Pending,80.0,1,Average,Tom,Active,NaN,2024-06-15
9958,CLM10958,PAT9586,POL8144,HSP394,Amit,22.0,Female,ravi,9876543210,Delhi,...,60.0,Online,Failed,72.0,3,Poor,Rahul,Active,NaN,2024-07-17
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,69.0,Card,Paid,93.0,0,Average,Tom,Closed,Yes,2026-02-21
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,27.0,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,69.0,Cash,NaN,6.0,0,Poor,NaN,Closed,No,2025-05-19

Poor Feedback

In [193]:
poor_feedback = df[df["Feedback"] == "Poor"]
poor_feedback

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
100,CLM1100,PAT8912,POL5225,HSP118,Fatima,58.0,Other,ravi,9876543210,NaN,...,100.0,Card,Failed,61.0,4,Poor,NaN,Active,Yes,2025-07-13
108,CLM1108,PAT6171,POL7273,HSP213,NaN,91.0,F,noemail@example.com,12345,NaN,...,NaN,Online,NaN,-6.0,4,Poor,Alex,Closed,No,2024-09-02
145,CLM1145,PAT4573,POL5607,HSP274,NaN,52.0,Other,john@,12345,Chennai,...,70.0,Cahs,Failed,77.0,2,Poor,Sita,Actve,No,2025-07-29
153,CLM1153,PAT5025,POL7288,HSP171,Ravi,112.0,Female,ravi,9876543210,London,...,17.0,Cahs,Failed,16.0,0,Poor,Rahul,Active,No,2025-03-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9757,CLM10757,PAT6484,POL4610,HSP384,Fatima,13.0,Male,amit@yahoo.com,12345,Delhi,...,38.0,NaN,Failed,73.0,0,Poor,Tom,Active,No,2024-05-13
9833,CLM10833,PAT355,POL6918,HSP463,Fatima,14.0,Mle,noemail@example.com,NaN,New York,...,58.0,Cahs,NaN,10.0,3,Poor,Alex,Inactive,No,2025-08-27
9882,CLM10882,PAT5786,POL2496,HSP447,Priya,96.0,Other,john@,NaN,Chennai,...,40.0,Online,Failed,13.0,4,Poor,Sita,Actve,Yes,2025-01-30
9958,CLM10958,PAT9586,POL8144,HSP394,Amit,22.0,Female,ravi,9876543210,Delhi,...,60.0,Online,Failed,72.0,3,Poor,Rahul,Active,NaN,2024-07-17
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,69.0,Cash,NaN,6.0,0,Poor,NaN,Closed,No,2025-05-19

Patients from Apollo Hospital

In [194]:
df["Hospital_Name"].replace({"Apollo":"Apollo Hospital", "Not Available":"Apollo Hospital"})

5                Fortis
15      Apollo Hospital
16                AIIMS
17               Fortis
42               Global
             ...
9959             Fortis
9962    Apollo Hospital
9965    Apollo Hospital
9967    Apollo Hospital
9984    Apollo Hospital
Name: Hospital_Name, Length: 1057, dtype: object

In [195]:
Hospital_Name = df[df["Hospital_Name"] == "Apollo"]
Hospital_Name

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,CoPay_Percentage,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,23.0,Card,Paid,98.0,3,Poor,Alex,Actve,Yes,2024-03-16
47,CLM1047,PAT8689,POL5800,HSP175,Priya,41.0,F,amit@yahoo.com,12345,Chennai,...,22.0,NaN,Failed,62.0,3,Average,Rahul,Closed,No,2024-02-14
100,CLM1100,PAT8912,POL5225,HSP118,Fatima,58.0,Other,ravi,9876543210,NaN,...,100.0,Card,Failed,61.0,4,Poor,NaN,Active,Yes,2025-07-13
117,CLM1117,PAT9013,POL3674,HSP419,Amit,63.0,Male,amit@yahoo.com,12345,Chennai,...,40.0,Cash,Pending,21.0,5,Good,Sita,Closed,NaN,2024-04-12
227,CLM1227,PAT6290,POL2097,HSP88,Ravi,68.0,Male,mary@gmail.com,12345,Delhi,...,16.0,Card,NaN,NaN,0,NaN,Sita,Closed,NaN,2026-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9703,CLM10703,PAT2428,POL2126,HSP56,NaN,44.0,Mle,mary@gmail.com,9876543210,NaN,...,20.0,Card,Paid,47.0,4,Average,Alex,Actve,Yes,2024-10-13
9769,CLM10769,PAT7942,POL4538,HSP494,NaN,114.0,Female,john@,12345,Delhi,...,118.0,Cahs,Pending,95.0,5,NaN,NaN,Inactive,Yes,2026-02-13
9816,CLM10816,PAT9340,POL8215,HSP125,NaN,62.0,Mle,noemail@example.com,12345,London,...,18.0,Card,Paid,61.0,0,NaN,NaN,Active,No,2024-06-21
9850,CLM10850,PAT2366,POL1458,HSP380,Mary,96.0,Other,john@,98765 43210,London,...,-7.0,Cahs,NaN,98.0,1,NaN,Alex,Closed,No,2025-12-31
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,27.0,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05

In [196]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date'],
      dtype='object')

#**Section D — Merge / Join Operations**

Merge Patient and Claim Details (Using Patient_ID)

In [197]:
patient_claim = df[[
    "Patient_ID",
    "Name",
    "Age",
    "Claim_ID",
    "Claim_Amount",
    "Approved_Amount"
]]

patient_claim.head()

   Patient_ID    Name   Age Claim_ID  Claim_Amount  Approved_Amount
5     PAT2610    Amit   1.0  CLM1005      108675.0             86.0
15     PAT601    Ravi  26.0  CLM1015      135058.0          35667.0
16    PAT4738  Fatima  22.0  CLM1016      193158.0           3062.0
17     PAT858    Amit  71.0  CLM1017      105738.0          70978.0
42    PAT6356     NaN  15.0  CLM1042      103206.0          10900.0

Merge Hospital Details (Using Hospital_ID)

In [198]:
hospital_data = df[[
    "Hospital_ID",
    "Hospital_Name",
    "City",
    "Country",
    "Claim_Amount"
]]

hospital_data.head()

   Hospital_ID Hospital_Name       City Country  Claim_Amount
5       HSP175        Fortis     Mumbai     USA      108675.0
15      HSP416        Apollo    Kolkata   India      135058.0
16      HSP405         AIIMS    Kolkata     USA      193158.0
17      HSP272        Fortis        NaN      uk      105738.0
42      HSP180        Global  Bangalore      uk      103206.0

Combine Insurance and Claim Data

In [199]:
insurance_claim = df[[
    "Insurance_Type",
    "Claim_ID",
    "Claim_Amount",
    "Approved_Amount"
]]

insurance_claim.head()

   Insurance_Type Claim_ID  Claim_Amount  Approved_Amount
5         Premium  CLM1005      108675.0             86.0
15        Premium  CLM1015      135058.0          35667.0
16        Premium  CLM1016      193158.0           3062.0
17        General  CLM1017      105738.0          70978.0
42        General  CLM1042      103206.0          10900.0

Total Claim Amount per Hospital

In [200]:
total_claim_hospital = df.groupby("Hospital_Name")["Claim_Amount"].sum()
total_claim_hospital.head()

Hospital_Name
AIIMS            3.136520e+07
Apollo           2.639197e+07
Fortis           2.670566e+07
Global           2.570700e+07
Not Available    2.961345e+07
Name: Claim_Amount, dtype: float64

Average Approved Amount per Insurance Type

In [201]:
avg_approved = df.groupby("Insurance_Type")["Approved_Amount"].mean()
avg_approved

Insurance_Type
Basic      69006.882784
General    65742.133459
Premium    64583.603175
Name: Approved_Amount, dtype: float64

Patients with Multiple Claims in a Year

In [202]:
df["Claim_Date"]=pd.to_datetime(df["Claim_Date"])

/tmp/ipykernel_14451/2177028068.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Claim_Date"]=pd.to_datetime(df["Claim_Date"])

In [203]:
df["Claim_Year"] = df["Claim_Date"].dt.year
multiple_claims = df.groupby(["Patient_ID", "Claim_Year"]).size()
multiple_claims = multiple_claims[multiple_claims > 1]
multiple_claims

/tmp/ipykernel_14451/2666405735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Claim_Year"] = df["Claim_Date"].dt.year

Patient_ID  Claim_Year
PAT1058     2024          2
PAT1250     2025          2
PAT1336     2025          2
PAT1876     2025          2
PAT260      2025          2
PAT2886     2025          2
PAT440      2025          2
PAT5489     2025          2
PAT5824     2024          2
PAT5947     2024          2
PAT6214     2024          2
PAT6536     2024          2
PAT6556     2025          2
PAT6621     2025          2
PAT7000     2024          2
PAT7645     2024          2
PAT7779     2024          2
PAT7998     2025          2
PAT8075     2025          2
PAT8415     2024          2
PAT8427     2024          2
PAT880      2024          2
PAT9187     2024          2
PAT9452     2024          2
PAT9792     2024          2
PAT9850     2025          2
dtype: int64

Hospitals with Highest Total Claims

In [204]:
df.groupby("Hospital_Name")["Claim_Amount"].sum().sort_values(ascending=False)

Hospital_Name
AIIMS            3.136520e+07
Not Available    2.961345e+07
Fortis           2.670566e+07
Apollo           2.639197e+07
Global           2.570700e+07
Name: Claim_Amount, dtype: float64

Patients Who Only Have “Rejected” Claims

In [205]:
rejected_only = df.groupby("Patient_ID")["Claim_Status"].apply(lambda x: (x == "Rejected").all())
rejected_only = rejected_only[rejected_only == True]
rejected_only

Patient_ID
PAT102     True
PAT1042    True
PAT1045    True
PAT1052    True
PAT1175    True
           ...
PAT9792    True
PAT989     True
PAT9947    True
PAT9948    True
PAT9970    True
Name: Claim_Status, Length: 260, dtype: bool

Claims with Missing Hospital Info

In [206]:
missing_hospital = df[df["Hospital_Name"].isnull()]
missing_hospital

Empty DataFrame
Columns: [Claim_ID, Patient_ID, Policy_ID, Hospital_ID, Name, Age, Gender, Email, Phone, Address, City, Country, Diagnosis, Disease_Category, Doctor_Name, Treatment_Start_Date, Treatment_End_Date, Hospital_Name, Insurance_Type, Claim_Amount, Approved_Amount, Claim_Status, Policy_Start_Date, Policy_End_Date, Deductible_Amount, CoPay_Percentage, Payment_Mode, Payment_Status, Reimbursement_Days, Patient_Satisfaction_Score, Feedback, Agent_Name, Account_Status, Followup_Required, Claim_Date, Claim_Year]
Index: []

[0 rows x 36 columns]

Claims with Missing Doctor Info

In [207]:
missing_doctor = df[df["Doctor_Name"].isnull()]
missing_doctor

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,Payment_Mode,Payment_Status,Reimbursement_Days,Patient_Satisfaction_Score,Feedback,Agent_Name,Account_Status,Followup_Required,Claim_Date,Claim_Year
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,Cahs,Pending,2.0,3,Average,Rahul,Closed,Yes,2024-08-11,2024
90,CLM1090,PAT1232,POL2990,HSP216,Mary,73.0,Mle,john@,98765 43210,Chennai,...,Card,Pending,25.0,4,Good,NaN,Inactive,NaN,2025-05-01,2025
136,CLM1136,PAT989,POL1039,HSP36,NaN,35.0,F,mary@gmail.com,NaN,Delhi,...,Cahs,Pending,59.0,4,NaN,Rahul,Active,Yes,2025-06-27,2025
208,CLM1208,PAT1619,POL2872,HSP290,Priya,20.0,Male,john@,98765 43210,London,...,NaN,Paid,91.0,3,Average,Sita,Active,Yes,2024-01-25,2024
342,CLM1342,PAT2886,POL8819,HSP285,Ravi,29.0,Male,mary@gmail.com,98765 43210,Mumbai,...,Card,Pending,25.0,2,Average,Sita,Inactive,Yes,2025-07-14,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9916,CLM10916,PAT3040,POL2556,HSP489,Mary,63.0,Mle,noemail@example.com,9876543210,NaN,...,NaN,Paid,-8.0,0,Average,Sita,Closed,NaN,2026-02-05,2026
9942,CLM10942,PAT4090,POL6760,HSP81,Mary,2.0,Mle,john@,NaN,NaN,...,NaN,Pending,22.0,3,Average,Alex,Active,No,2025-03-13,2025
9954,CLM10954,PAT2037,POL3895,HSP195,John,12.0,Female,mary@gmail.com,9876543210,New York,...,Card,Pending,17.0,0,Average,Tom,Inactive,No,2025-11-26,2025
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,Online,Pending,32.0,0,Average,Sita,Actve,Yes,2025-05-05,2025
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,Online,Paid,22.0,3,Average,Sita,Closed,Yes,2025-07-19,2025

In [208]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year'],
      dtype='object')

#**Section E — Calculated Columns**

Claim Difference

In [209]:
df["Claim_Difference"] = df["Claim_Amount"] - df["Approved_Amount"]
df["Claim_Difference"]

/tmp/ipykernel_14451/3811854236.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Claim_Difference"] = df["Claim_Amount"] - df["Approved_Amount"]

5       108589.0
15       99391.0
16      190096.0
17       34760.0
42       92306.0
          ...
9959    142903.0
9962    141373.0
9965     15292.0
9967     33117.0
9984     18700.0
Name: Claim_Difference, Length: 1057, dtype: float64

Treatment Duration

In [210]:
df["Treatment_Duration"] = df["Treatment_End_Date"] - df["Treatment_Start_Date"]
df["Treatment_Duration"]

/tmp/ipykernel_14451/159543881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Treatment_Duration"] = df["Treatment_End_Date"] - df["Treatment_Start_Date"]

5      457 days
15     767 days
16      23 days
17     432 days
42     286 days
         ...
9959   331 days
9962   189 days
9965   228 days
9967   459 days
9984   371 days
Name: Treatment_Duration, Length: 1057, dtype: timedelta64[ns]

Policy Duration

In [211]:
df["Policy_Duration"] = df["Policy_End_Date"] - df["Policy_Start_Date"]
df["Policy_Duration"]

/tmp/ipykernel_14451/1241102250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Policy_Duration"] = df["Policy_End_Date"] - df["Policy_Start_Date"]

5       776 days
15      940 days
16     1421 days
17     1063 days
42      695 days
          ...
9959    518 days
9962    528 days
9965   1524 days
9967    883 days
9984   2393 days
Name: Policy_Duration, Length: 1057, dtype: timedelta64[ns]

Age Group

In [212]:
conditions = [(df['Age'] >= 0) & (df['Age'] <= 17), (df['Age'] >= 18) & (df['Age'] <= 64), (df['Age'] >= 65)]
choices = ['Child', 'Adult', 'Senior']
df['Age_Group'] = np.select(conditions, choices, default='Unknown')
df['Age_Group']

/tmp/ipykernel_14451/290493194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age_Group'] = np.select(conditions, choices, default='Unknown')

5        Child
15       Adult
16       Adult
17      Senior
42       Child
         ...
9959    Senior
9962    Senior
9965     Adult
9967    Senior
9984     Adult
Name: Age_Group, Length: 1057, dtype: object

Encode Gender

In [213]:
df["Gender_Code"] = df["Gender"].map({"Male": 1,"Female": 0})
df["Gender_Code"]

/tmp/ipykernel_14451/1125035140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender_Code"] = df["Gender"].map({"Male": 1,"Female": 0})

5       1.0
15      NaN
16      1.0
17      NaN
42      1.0
       ...
9959    NaN
9962    NaN
9965    NaN
9967    1.0
9984    NaN
Name: Gender_Code, Length: 1057, dtype: float64

Encode Claim Status

In [214]:
df["Claim_Status_Code"] = df["Claim_Status"].astype("category").cat.codes
df["Claim_Status_Code"]

/tmp/ipykernel_14451/3114830587.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Claim_Status_Code"] = df["Claim_Status"].astype("category").cat.codes

5       3
15      1
16      1
17      2
42      2
       ..
9959    3
9962    1
9965    1
9967    2
9984    3
Name: Claim_Status_Code, Length: 1057, dtype: int8

In [215]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

#**Section F — Sorting & Aggregation**

Top 10 Hospitals by Claim Amount

In [216]:
df.groupby("Hospital_Name")["Claim_Amount"].sum().sort_values(ascending=False).head(10)

Hospital_Name
AIIMS            3.136520e+07
Not Available    2.961345e+07
Fortis           2.670566e+07
Apollo           2.639197e+07
Global           2.570700e+07
Name: Claim_Amount, dtype: float64

Top 10 Patients by Claim

In [217]:
df.groupby("Patient_ID")["Claim_Amount"].sum().sort_values(ascending=False).head(10)

Patient_ID
PAT9648    446874.0
PAT5938    397150.0
PAT7000    395593.0
PAT3015    381012.0
PAT9935    369564.0
PAT6536    361473.0
PAT3218    361118.0
PAT7643    361020.0
PAT9141    353131.0
PAT4744    346003.0
Name: Claim_Amount, dtype: float64

Average Claim by Disease

In [218]:
df.groupby("Disease_Category")["Claim_Amount"].mean()

Disease_Category
Acute         129552.250379
Chronic       131560.117533
Infectious    134504.600062
Name: Claim_Amount, dtype: float64

Most Common Insurance Type

In [219]:
df["Insurance_Type"].value_counts()

Insurance_Type
General    532
Basic      273
Premium    252
Name: count, dtype: int64

Patients with More Than 3 Claims

In [220]:
claim_counts = df["Patient_ID"].value_counts()
patients_more_than3 = claim_counts[claim_counts >= 3]
patients_more_than3

Patient_ID
PAT9648    3
Name: count, dtype: int64

In [221]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

#**Section G — Advanced Cleaning / Validation**

Validate Approved_Amount ≤ Claim_Amount

In [222]:
invalid_claims = df[df["Approved_Amount"] <= df["Claim_Amount"]]
invalid_claims

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,Account_Status,Followup_Required,Claim_Date,Claim_Year,Claim_Difference,Treatment_Duration,Policy_Duration,Age_Group,Gender_Code,Claim_Status_Code
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,Inactive,Yes,2025-08-08,2025,108589.0,457 days,776 days,Child,1.0,3
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,Actve,Yes,2024-03-16,2024,99391.0,767 days,940 days,Adult,NaN,1
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,Actve,Yes,2024-12-15,2024,190096.0,23 days,1421 days,Adult,1.0,1
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,Actve,No,2026-02-14,2026,34760.0,432 days,1063 days,Senior,NaN,2
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,Closed,Yes,2024-08-11,2024,92306.0,286 days,695 days,Child,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,Closed,Yes,2026-02-21,2026,142903.0,331 days,518 days,Senior,NaN,3
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,Actve,Yes,2025-05-05,2025,141373.0,189 days,528 days,Senior,NaN,1
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,Closed,No,2025-05-19,2025,15292.0,228 days,1524 days,Adult,NaN,1
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,Closed,Yes,2025-07-19,2025,33117.0,459 days,883 days,Senior,1.0,2
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,Active,NaN,2024-10-23,2024,18700.0,371 days,2393 days,Adult,NaN,3

In [223]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

Validate Policy_Duration > 0

In [224]:
df["Policy_Duration"] = df["Policy_End_Date"] - df["Policy_Start_Date"]
df["Policy_Duration"]
invalid_policy = df[df["Policy_Duration"] >= pd.Timedelta(days=0)]
invalid_policy

/tmp/ipykernel_14451/3025255639.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Policy_Duration"] = df["Policy_End_Date"] - df["Policy_Start_Date"]

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,Account_Status,Followup_Required,Claim_Date,Claim_Year,Claim_Difference,Treatment_Duration,Policy_Duration,Age_Group,Gender_Code,Claim_Status_Code
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,Inactive,Yes,2025-08-08,2025,108589.0,457 days,776 days,Child,1.0,3
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,Actve,Yes,2024-03-16,2024,99391.0,767 days,940 days,Adult,NaN,1
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,Actve,Yes,2024-12-15,2024,190096.0,23 days,1421 days,Adult,1.0,1
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,Actve,No,2026-02-14,2026,34760.0,432 days,1063 days,Senior,NaN,2
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,Closed,Yes,2024-08-11,2024,92306.0,286 days,695 days,Child,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,Closed,Yes,2026-02-21,2026,142903.0,331 days,518 days,Senior,NaN,3
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,Actve,Yes,2025-05-05,2025,141373.0,189 days,528 days,Senior,NaN,1
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,Closed,No,2025-05-19,2025,15292.0,228 days,1524 days,Adult,NaN,1
9967,CLM10967,PAT1960,POL4041,HSP243,Ravi,82.0,Male,noemail@example.com,9876543210,Delhi,...,Closed,Yes,2025-07-19,2025,33117.0,459 days,883 days,Senior,1.0,2
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,Active,NaN,2024-10-23,2024,18700.0,371 days,2393 days,Adult,NaN,3

In [225]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

Check if Treatment_Duration > Policy_Duration (Flag Error)

In [226]:
df["Treatment_Duration"] = df["Treatment_End_Date"] - df["Treatment_Start_Date"]
df["Treatment_Duration"]
invalid_treatment = df[df["Treatment_Duration"] >= df["Policy_Duration"]]
invalid_treatment

/tmp/ipykernel_14451/387371673.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Treatment_Duration"] = df["Treatment_End_Date"] - df["Treatment_Start_Date"]

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,Account_Status,Followup_Required,Claim_Date,Claim_Year,Claim_Difference,Treatment_Duration,Policy_Duration,Age_Group,Gender_Code,Claim_Status_Code
47,CLM1047,PAT8689,POL5800,HSP175,Priya,41.0,F,amit@yahoo.com,12345,Chennai,...,Closed,No,2024-02-14,2024,13922.626481,453 days,27 days,Adult,NaN,3
90,CLM1090,PAT1232,POL2990,HSP216,Mary,73.0,Mle,john@,98765 43210,Chennai,...,Inactive,NaN,2025-05-01,2025,3466.000000,814 days,269 days,Senior,NaN,1
208,CLM1208,PAT1619,POL2872,HSP290,Priya,20.0,Male,john@,98765 43210,London,...,Active,Yes,2024-01-25,2024,151341.000000,651 days,111 days,Adult,1.0,3
235,CLM1235,PAT6115,POL2420,HSP406,Ravi,98.0,Other,mary@gmail.com,98765 43210,Delhi,...,Inactive,No,2025-03-09,2025,59471.000000,858 days,724 days,Senior,NaN,0
287,CLM1287,PAT3286,POL8829,HSP93,Ravi,61.0,Male,mary@gmail.com,12345,London,...,Inactive,No,2025-10-22,2025,4383.000000,891 days,844 days,Adult,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,CLM10835,PAT9480,POL4890,HSP199,Ravi,27.0,Male,amit@yahoo.com,NaN,Mumbai,...,Closed,Yes,2025-02-12,2025,93733.000000,819 days,352 days,Adult,1.0,2
9882,CLM10882,PAT5786,POL2496,HSP447,Priya,96.0,Other,john@,NaN,Chennai,...,Actve,Yes,2025-01-30,2025,81921.000000,810 days,280 days,Senior,NaN,2
9916,CLM10916,PAT3040,POL2556,HSP489,Mary,63.0,Mle,noemail@example.com,9876543210,NaN,...,Closed,NaN,2026-02-05,2026,85720.000000,326 days,215 days,Adult,NaN,1
9954,CLM10954,PAT2037,POL3895,HSP195,John,12.0,Female,mary@gmail.com,9876543210,New York,...,Inactive,No,2025-11-26,2025,21102.000000,887 days,389 days,Child,0.0,2
9955,CLM10955,PAT703,POL3139,HSP161,John,82.0,Male,mary@gmail.com,12345,London,...,Actve,No,2024-08-13,2024,11415.000000,384 days,49 days,Senior,1.0,2

In [227]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

Check Invalid Phone Numbers

In [228]:
invalid_phone = df[df["Phone"].astype(str).str.len() != 10]
invalid_phone

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,Account_Status,Followup_Required,Claim_Date,Claim_Year,Claim_Difference,Treatment_Duration,Policy_Duration,Age_Group,Gender_Code,Claim_Status_Code
5,CLM1005,PAT2610,POL6070,HSP175,Amit,1.0,Male,amit@yahoo.com,98765 43210,Delhi,...,Inactive,Yes,2025-08-08,2025,108589.0,457 days,776 days,Child,1.0,3
15,CLM1015,PAT601,POL2930,HSP416,Ravi,26.0,Other,john@,98765 43210,Chennai,...,Actve,Yes,2024-03-16,2024,99391.0,767 days,940 days,Adult,NaN,1
16,CLM1016,PAT4738,POL9359,HSP405,Fatima,22.0,Male,ravi,NaN,NaN,...,Actve,Yes,2024-12-15,2024,190096.0,23 days,1421 days,Adult,1.0,1
17,CLM1017,PAT858,POL7321,HSP272,Amit,71.0,Other,amit@yahoo.com,12345,New York,...,Actve,No,2026-02-14,2026,34760.0,432 days,1063 days,Senior,NaN,2
42,CLM1042,PAT6356,POL9000,HSP180,NaN,15.0,Male,ravi,12345,London,...,Closed,Yes,2024-08-11,2024,92306.0,286 days,695 days,Child,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9957,CLM10957,PAT9088,POL5705,HSP232,John,67.0,Female,amit@yahoo.com,NaN,NaN,...,Active,NaN,2024-06-15,2024,81773.0,938 days,1330 days,Senior,0.0,1
9959,CLM10959,PAT1576,POL3064,HSP472,Priya,81.0,Mle,amit@yahoo.com,98765 43210,Chennai,...,Closed,Yes,2026-02-21,2026,142903.0,331 days,518 days,Senior,NaN,3
9962,CLM10962,PAT4561,POL1173,HSP407,John,74.0,F,mary@gmail.com,NaN,Mumbai,...,Actve,Yes,2025-05-05,2025,141373.0,189 days,528 days,Senior,NaN,1
9965,CLM10965,PAT167,POL3796,HSP440,Fatima,30.0,Mle,mary@gmail.com,NaN,Delhi,...,Closed,No,2025-05-19,2025,15292.0,228 days,1524 days,Adult,NaN,1
9984,CLM10984,PAT1052,POL5504,HSP472,NaN,20.0,Other,amit@yahoo.com,98765 43210,Mumbai,...,Active,NaN,2024-10-23,2024,18700.0,371 days,2393 days,Adult,NaN,3

In [229]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

In [234]:
df.columns

Index(['Claim_ID', 'Patient_ID', 'Policy_ID', 'Hospital_ID', 'Name', 'Age',
       'Gender', 'Email', 'Phone', 'Address', 'City', 'Country', 'Diagnosis',
       'Disease_Category', 'Doctor_Name', 'Treatment_Start_Date',
       'Treatment_End_Date', 'Hospital_Name', 'Insurance_Type', 'Claim_Amount',
       'Approved_Amount', 'Claim_Status', 'Policy_Start_Date',
       'Policy_End_Date', 'Deductible_Amount', 'CoPay_Percentage',
       'Payment_Mode', 'Payment_Status', 'Reimbursement_Days',
       'Patient_Satisfaction_Score', 'Feedback', 'Agent_Name',
       'Account_Status', 'Followup_Required', 'Claim_Date', 'Claim_Year',
       'Claim_Difference', 'Treatment_Duration', 'Policy_Duration',
       'Age_Group', 'Gender_Code', 'Claim_Status_Code'],
      dtype='object')

In [232]:
df = df[df["CoPay_Percentage"] <= 100]

Verify Missing Payment_Status for Completed Claims

In [233]:
missing_payment = df[
    (df["Claim_Status"] == "Approved") &
    (df["Payment_Status"].isnull())]
missing_payment

,Claim_ID,Patient_ID,Policy_ID,Hospital_ID,Name,Age,Gender,Email,Phone,Address,...,Account_Status,Followup_Required,Claim_Date,Claim_Year,Claim_Difference,Treatment_Duration,Policy_Duration,Age_Group,Gender_Code,Claim_Status_Code
227,CLM1227,PAT6290,POL2097,HSP88,Ravi,68.0,Male,mary@gmail.com,12345,Delhi,...,Closed,NaN,2026-03-01,2026,116125.0,148 days,1043 days,Senior,1.0,0
523,CLM1523,PAT710,POL2871,HSP379,Priya,70.0,Other,mary@gmail.com,12345,NaN,...,Inactive,No,2025-05-13,2025,80240.0,246 days,998 days,Senior,NaN,0
1061,CLM2061,PAT7216,POL2396,HSP68,Mary,104.0,Female,amit@yahoo.com,98765 43210,NaN,...,Inactive,Yes,2024-08-06,2024,150067.0,378 days,735 days,Senior,0.0,0
1856,CLM2856,PAT6297,POL6830,HSP52,Fatima,63.0,Other,amit@yahoo.com,9876543210,London,...,Actve,No,2026-01-16,2026,20706.0,440 days,1671 days,Adult,NaN,0
2894,CLM3894,PAT9445,POL3798,HSP10,Mary,3.0,F,mary@gmail.com,98765 43210,Chennai,...,Closed,No,2024-07-08,2024,92048.0,398 days,2075 days,Child,NaN,0
3132,CLM4132,PAT7579,POL6731,HSP485,John,105.0,Other,john@,9876543210,NaN,...,Active,Yes,2024-05-21,2024,144681.0,716 days,1286 days,Senior,NaN,0
3175,CLM4175,PAT7678,POL8735,HSP38,NaN,4.0,Mle,noemail@example.com,12345,New York,...,Closed,No,2024-01-30,2024,132935.0,724 days,278 days,Child,NaN,0
3382,CLM4382,PAT9853,POL2687,HSP351,Amit,82.0,Other,john@,NaN,London,...,Actve,Yes,2025-08-07,2025,135650.0,666 days,990 days,Senior,NaN,0
3755,CLM4755,PAT3226,POL8822,HSP354,Priya,30.0,F,john@,9876543210,Delhi,...,Actve,Yes,2024-07-13,2024,55910.0,631 days,18 days,Adult,NaN,0
3759,CLM4759,PAT6737,POL5780,HSP59,Fatima,104.0,Female,amit@yahoo.com,12345,Chennai,...,Active,Yes,2024-05-12,2024,24481.0,608 days,936 days,Senior,0.0,0
4005,CLM5005,PAT2878,POL9685,HSP389,Fatima,52.0,Mle,noemail@example.com,9876543210,NaN,...,Actve,NaN,2025-09-08,2025,110513.0,300 days,128 days,Adult,NaN,0
4413,CLM5413,PAT8587,POL1305,HSP142,John,39.0,Female,amit@yahoo.com,98765 43210,Mumbai,...,Active,NaN,2025-03-10,2025,151524.0,452 days,1935 days,Adult,0.0,0
4633,CLM5633,PAT1587,POL3857,HSP442,Amit,30.0,Mle,amit@yahoo.com,NaN,New York,...,Actve,No,2025-11-21,2025,18307.0,180 days,995 days,Adult,NaN,0
4793,CLM5793,PAT7934,POL3444,HSP336,Amit,46.0,Mle,mary@gmail.com,9876543210,New York,...,Inactive,No,2024-06-09,2024,100644.0,218 days,242 days,Adult,NaN,0
5191,CLM6191,PAT1900,POL5929,HSP200,NaN,63.0,Male,john@,9876543210,London,...,Inactive,NaN,2024-08-22,2024,88683.0,976 days,948 days,Adult,1.0,0
5376,CLM6376,PAT8427,POL9499,HSP177,Amit,56.0,F,john@,9876543210,Delhi,...,Closed,No,2024-05-31,2024,16715.0,271 days,100 days,Adult,NaN,0
5401,CLM6401,PAT8518,POL2610,HSP266,Fatima,104.0,Female,mary@gmail.com,12345,Mumbai,...,Inactive,NaN,2025-03-27,2025,71048.0,308 days,1552 days,Senior,0.0,0
5731,CLM6731,PAT4347,POL6186,HSP52,John,23.0,F,ravi,9876543210,Delhi,...,Actve,No,2024-08-10,2024,29571.0,161 days,1617 days,Adult,NaN,0
5764,CLM6764,PAT2437,POL9586,HSP275,John,102.0,F,john@,NaN,London,...,Active,Yes,2025-09-10,2025,66467.0,31 days,2120 days,Senior,NaN,0
6164,CLM7164,PAT1545,POL4380,HSP160,Priya,91.0,Male,amit@yahoo.com,NaN,Delhi,...,Inactive,No,2024-08-30,2024,38296.0,278 days,1596 days,Senior,1.0,0
6470,CLM7470,PAT5630,POL9653,HSP472,John,21.0,Other,noemail@example.com,NaN,Mumbai,...,Inactive,No,2025-12-24,2025,19315.0,278 days,820 days,Adult,NaN,0
6697,CLM7697,PAT9260,POL4103,HSP151,Amit,119.0,Female,mary@gmail.com,12345,Chennai,...,Actve,No,2025-11-11,2025,28819.0,102 days,466 days,Senior,0.0,0
6887,CLM7887,PAT9176,POL2825,HSP376,NaN,69.0,F,amit@yahoo.com,NaN,London,...,Inactive,No,2026-02-24,2026,122570.0,561 days,1492 days,Senior,NaN,0
7140,CLM8140,PAT1410,POL6383,HSP181,Priya,71.0,Mle,john@,98765 43210,Mumbai,...,Closed,NaN,2024-10-27,2024,141708.0,199 days,1523 days,Senior,NaN,0
7181,CLM8181,PAT1220,POL3410,HSP82,Ravi,86.0,F,amit@yahoo.com,9876543210,Mumbai,...,Actve,Yes,2025-01-02,2025,65107.0,99 days,433 days,Senior,NaN,0
7866,CLM8866,PAT2066,POL5455,HSP253,NaN,24.0,Male,mary@gmail.com,98765 43210,New York,...,Inactive,No,2025-08-31,2025,115127.0,885 days,1061 days,Adult,1.0,0
7904,CLM8904,PAT5417,POL8025,HSP47,Fatima,46.0,F,noemail@example.com,9876543210,Delhi,...,Actve,Yes,2025-07-27,2025,116149.0,278 days,413 days,Adult,NaN,0
8101,CLM9101,PAT8062,POL1124,HSP263,NaN,96.0,F,john@,12345,Mumbai,...,Actve,NaN,2026-02-01,2026,25858.0,763 days,1105 days,Senior,NaN,0
8192,CLM9192,PAT667,POL9400,HSP492,NaN,3.0,Female,amit@yahoo.com,9876543210,NaN,...,Active,NaN,2025-10-21,2025,128470.0,443 days,364 days,Child,0.0,0
8300,CLM9300,PAT6859,POL3406,HSP306,Priya,29.0,Mle,noemail@example.com,9876543210,New York,...,Closed,Yes,2025-12-29,2025,128244.0,891 days,624 days,Adult,NaN,0
8767,CLM9767,PAT1883,POL6755,HSP6,Fatima,85.0,Other,ravi,9876543210,London,...,Closed,Yes,2024-08-01,2024,164990.0,663 days,945 days,Senior,NaN,0
8796,CLM9796,PAT8793,POL9237,HSP85,Mary,76.0,Mle,mary@gmail.com,9876543210,New York,...,Closed,Yes,2024-10-21,2024,1206.0,401 days,1409 days,Senior,NaN,0
9063,CLM10063,PAT8848,POL6923,HSP359,John,43.0,Female,noemail@example.com,98765 43210,Chennai,...,Active,Yes,2025-04-02,2025,98844.0,657 days,283 days,Adult,0.0,0
9446,CLM10446,PAT5159,POL3982,HSP306,Mary,106.0,F,mary@gmail.com,9876543210,New York,...,Actve,Yes,2025-10-01,2025,60266.0,163 days,722 days,Senior,NaN,0
9577,CLM10577,PAT9599,POL5939,HSP338,Priya,56.0,Male,mary@gmail.com,12345,London,...,Inactive,No,2025-03-26,2025,7023.0,871 days,292 days,Adult,1.0,0
9850,CLM10850,PAT2366,POL1458,HSP380,Mary,96.0,Other,john@,98765 43210,London,...,Closed,No,2025-12-31,2025,164374.0,871 days,1777 days,Senior,NaN,0

Final Step — Save Clean Dataset

In [235]:
from google.colab import files
df.to_excel("cleaned_file.xlsx", index=False)
files.download("cleaned_file.xlsx")